// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "admin": { "tabs": Array<{ "id": string; "label": string; "path": string }> }; "ai_tutor": { "suggestedQuestions": Array<string> } };
  export const admin: { "tabs": Array<{ "id": string; "label": string; "path": string }> };
  export const ai_tutor: { "suggestedQuestions": Array<string> };
}
