-- Generated from SQLite source database: D:\PROJECTS\StudyHub_AI\StudyHub_AI\studyhub.db
-- This file contains controlled data migration statements for the verified Supabase schema.

INSERT INTO public.users (id, name, email, password_hash, role, avatar, program, year, department, streak, status, joined, created_at) VALUES ('u1', 'Alex Johnson', 'student@studyhub.ai', '$2b$10$gQwbw5GWnLCrgmDOesi3k.QZr6FPxAqFkY1UrawzRkqqr79wkFPDq', 'student', 'AJ', 'Computer Science', 2, '', 7, 'active', '2025-09-01', '2026-09-13 17:10:48') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.users (id, name, email, password_hash, role, avatar, program, year, department, streak, status, joined, created_at) VALUES ('u2', 'Dr. Sarah Mitchell', 'lecturer@studyhub.ai', '$2b$10$ZXotZSQ.uyiiXk9C62cuNuNi1it2HXnY6MGtn.5dwMpTmJKclvR.a', 'lecturer', 'SM', '', 0, 'Computer Science', 0, 'active', '2020-01-15', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.users (id, name, email, password_hash, role, avatar, program, year, department, streak, status, joined, created_at) VALUES ('u3', 'Admin User', 'admin@studyhub.ai', '$2b$10$BrhrY23hvGdPA6e9o2kQd.KepgX5kwp5YYn8SvUSnvGdDRos.Apui', 'admin', 'AU', '', 0, 'IT', 0, 'active', '2019-06-01', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.users (id, name, email, password_hash, role, avatar, program, year, department, streak, status, joined, created_at) VALUES ('u4', 'Maria Garcia', 'maria@studyhub.ai', '$2b$10$7khNlh3/X7j4xv/spBhjDuR5sG9AU/NSdsyUhwmGIo.nzqZ0tf5d2', 'student', 'MG', 'Data Science', 3, '', 12, 'active', '2024-09-01', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.users (id, name, email, password_hash, role, avatar, program, year, department, streak, status, joined, created_at) VALUES ('u5', 'James Carter', 'james@studyhub.ai', '$2b$10$i9wHCz8BzjP5G1gpOp0f5eOgpcLyOKrJp4lBFl9hAjFrbgAWbLG76', 'student', 'JC', 'Software Engineering', 1, '', 3, 'suspended', '2026-01-10', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.courses (id, code, title, color, progress, notes_count, assignments_count, icon, lecturer) VALUES ('cs301', 'CS301', 'Data Structures & Algorithms', '#1F6F6B', 72, 12, 4, 'Layers', 'Dr. Sarah Mitchell') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.courses (id, code, title, color, progress, notes_count, assignments_count, icon, lecturer) VALUES ('cs302', 'CS302', 'Database Management Systems', '#6FA37C', 58, 9, 3, 'Database', 'Prof. James Carter') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.courses (id, code, title, color, progress, notes_count, assignments_count, icon, lecturer) VALUES ('cs303', 'CS303', 'Operating Systems', '#E85D42', 45, 7, 5, 'Cpu', 'Dr. Emily Chen') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.courses (id, code, title, color, progress, notes_count, assignments_count, icon, lecturer) VALUES ('cs304', 'CS304', 'Computer Networks', '#FFC94A', 63, 10, 3, 'Network', 'Prof. Michael Brown') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n1', 'Binary Trees & BST', 'CS301', 'pdf', '2026-08-10', '2.4 MB', 18) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n2', 'Sorting Algorithms', 'CS301', 'slides', '2026-08-15', '1.1 MB', 32) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n3', 'Graph Theory Basics', 'CS301', 'pdf', '2026-08-18', '3.2 MB', 24) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n4', 'SQL Fundamentals', 'CS302', 'pdf', '2026-08-12', '1.8 MB', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n5', 'ER Diagrams & Normalization', 'CS302', 'slides', '2026-08-17', '900 KB', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n6', 'Process Scheduling', 'CS303', 'pdf', '2026-08-14', '2.1 MB', 16) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n7', 'Memory Management', 'CS303', 'slides', '2026-08-20', '1.5 MB', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.notes (id, title, course, type, date, size, pages) VALUES ('n8', 'TCP/IP Protocol Suite', 'CS304', 'pdf', '2026-08-16', '2.8 MB', 30) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.assignments (id, title, course, due_date, status, grade, max_grade, weight) VALUES ('a1', 'BST Implementation', 'CS301', '2026-09-05', 'submitted', 88, 100, '15%') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assignments (id, title, course, due_date, status, grade, max_grade, weight) VALUES ('a2', 'Sorting Benchmark Report', 'CS301', '2026-09-20', 'pending', NULL, 100, '20%') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assignments (id, title, course, due_date, status, grade, max_grade, weight) VALUES ('a3', 'Database Design Project', 'CS302', '2026-09-10', 'in-progress', NULL, 100, '25%') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assignments (id, title, course, due_date, status, grade, max_grade, weight) VALUES ('a4', 'SQL Query Optimization', 'CS302', '2026-09-25', 'pending', NULL, 100, '15%') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assignments (id, title, course, due_date, status, grade, max_grade, weight) VALUES ('a5', 'Process Scheduler Simulation', 'CS303', '2026-09-15', 'submitted', 76, 100, '20%') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quizzes (id, title, course, difficulty, question_count, duration, best_score, ai_generated) VALUES ('q1', 'Binary Trees Fundamentals', 'CS301', 'Medium', 3, 10, 67, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quizzes (id, title, course, difficulty, question_count, duration, best_score, ai_generated) VALUES ('q2', 'SQL Queries & Joins', 'CS302', 'Easy', 3, 8, 100, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quizzes (id, title, course, difficulty, question_count, duration, best_score, ai_generated) VALUES ('q3', 'Process Scheduling', 'CS303', 'Hard', 3, 12, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quizzes (id, title, course, difficulty, question_count, duration, best_score, ai_generated) VALUES ('q4', 'Network Protocols', 'CS304', 'Medium', 3, 10, NULL, TRUE) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq1', 'q1', 'What is the time complexity of searching in a balanced BST?', CAST('["O(n)","O(log n)","O(n log n)","O(1)"]' AS jsonb), 1, 'In a balanced BST, each comparison eliminates half the remaining nodes.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq10', 'q4', 'At which OSI layer does TCP operate?', CAST('["Network","Transport","Session","Application"]' AS jsonb), 1, 'TCP operates at the Transport layer (Layer 4) of the OSI model.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq11', 'q4', 'What does DNS stand for?', CAST('["Dynamic Network Service","Domain Name System","Data Network Standard","Distributed Node Service"]' AS jsonb), 1, 'DNS (Domain Name System) translates human-readable domain names to IP addresses.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq12', 'q4', 'Which protocol is connectionless?', CAST('["TCP","HTTP","UDP","FTP"]' AS jsonb), 2, 'UDP (User Datagram Protocol) is connectionless — it sends packets without establishing a connection.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq2', 'q1', 'Which traversal visits nodes in ascending order for a BST?', CAST('["Pre-order","Post-order","In-order","Level-order"]' AS jsonb), 2, 'In-order traversal (left, root, right) visits BST nodes in sorted ascending order.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq3', 'q1', 'What is the maximum number of nodes in a binary tree of height h?', CAST('["2h","2h - 1","2^h - 1","2^(h+1) - 1"]' AS jsonb), 3, 'A complete binary tree of height h has at most 2^(h+1) - 1 nodes.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq4', 'q2', 'Which SQL clause is used to filter rows?', CAST('["ORDER BY","GROUP BY","WHERE","HAVING"]' AS jsonb), 2, 'WHERE filters individual rows before grouping.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq5', 'q2', 'What does INNER JOIN return?', CAST('["All rows from left table","All rows from right table","Matching rows from both tables","All rows from both tables"]' AS jsonb), 2, 'INNER JOIN returns only rows where the join condition is met in both tables.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq6', 'q2', 'Which normal form eliminates transitive dependencies?', CAST('["1NF","2NF","3NF","BCNF"]' AS jsonb), 2, '3NF removes transitive dependencies where non-key attributes depend on other non-key attributes.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq7', 'q3', 'Which scheduling algorithm can cause starvation?', CAST('["Round Robin","FCFS","Priority Scheduling","SJF"]' AS jsonb), 2, 'Priority Scheduling can starve low-priority processes if high-priority ones keep arriving.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq8', 'q3', 'What is the main advantage of Round Robin scheduling?', CAST('["Minimizes waiting time","Ensures fairness","Maximizes CPU utilization","Reduces context switches"]' AS jsonb), 1, 'Round Robin gives each process an equal time slice, ensuring fair CPU distribution.', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quiz_questions (id, quiz_id, question, options, correct, explanation, order_idx) VALUES ('qq9', 'q3', 'In SJF scheduling, what information is required?', CAST('["Process priority","Burst time","Arrival time","Memory size"]' AS jsonb), 1, 'SJF (Shortest Job First) requires knowing the CPU burst time of each process.', 2) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f1', 'CS301', 'What is a Binary Search Tree?', 'A BST is a binary tree where each node''s left subtree contains only nodes with keys less than the node''s key, and the right subtree only nodes with greater keys.', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f2', 'CS301', 'What is Big O notation?', 'Big O notation describes the upper bound of an algorithm''s time or space complexity, expressing how performance scales with input size.', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f3', 'CS301', 'What is a Hash Table?', 'A data structure that maps keys to values using a hash function, providing O(1) average-case lookup, insertion, and deletion.', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f4', 'CS302', 'What is a Primary Key?', 'A primary key is a column (or set of columns) that uniquely identifies each row in a database table. It cannot be NULL.', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f5', 'CS302', 'What is database normalization?', 'The process of organizing a database to reduce redundancy and improve data integrity by dividing large tables into smaller ones and defining relationships.', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f6', 'CS303', 'What is a deadlock?', 'A deadlock occurs when two or more processes are blocked, each waiting for a resource held by another, creating a circular dependency.', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f7', 'CS303', 'What is virtual memory?', 'Virtual memory is a memory management technique that gives processes the illusion of a large, contiguous address space by using disk storage as an extension of RAM.', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.flashcards (id, deck, front, back, ai_generated) VALUES ('f8', 'CS304', 'What is the difference between TCP and UDP?', 'TCP is connection-oriented, reliable, and ordered. UDP is connectionless, faster, but unreliable. TCP is used for web/email; UDP for streaming/gaming.', TRUE) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v1', 'Binary Search Trees - Full Course', 'CS Dojo', '', '45:22', '1.2M', 98, 'CS301', '2 years ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v2', 'Sorting Algorithms Visualized', 'Reducible', '', '28:14', '890K', 95, 'CS301', '1 year ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v3', 'SQL Tutorial for Beginners', 'Programming with Mosh', '', '3:10:00', '5.4M', 97, 'CS302', '3 years ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v4', 'Database Normalization Explained', 'Decomplexify', '', '22:45', '340K', 93, 'CS302', '8 months ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v5', 'Operating Systems: CPU Scheduling', 'Neso Academy', '', '18:30', '620K', 96, 'CS303', '2 years ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.videos (id, title, channel, thumbnail, duration, views, relevance, course, uploaded_ago) VALUES ('v6', 'Computer Networking Full Course', 'freeCodeCamp', '', '9:25:00', '2.1M', 94, 'CS304', '1 year ago') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.study_plan (id, user_id, title, course, due_date, time, duration, type, completed) VALUES ('sp1', 'u1', 'Review BST lecture notes', 'CS301', '2026-08-24', '09:00', 60, 'study', TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.study_plan (id, user_id, title, course, due_date, time, duration, type, completed) VALUES ('sp2', 'u1', 'Complete Database Design Project', 'CS302', '2026-09-05', '14:00', 120, 'assignment', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.study_plan (id, user_id, title, course, due_date, time, duration, type, completed) VALUES ('sp3', 'u1', 'Watch OS Scheduling video', 'CS303', '2026-08-25', '11:00', 30, 'video', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.study_plan (id, user_id, title, course, due_date, time, duration, type, completed) VALUES ('sp4', 'u1', 'Binary Trees quiz practice', 'CS301', '2026-08-26', '16:00', 45, 'quiz', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.study_plan (id, user_id, title, course, due_date, time, duration, type, completed) VALUES ('sp5', 'u1', 'Read TCP/IP chapter', 'CS304', '2026-08-27', '10:00', 90, 'study', FALSE) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.forum_threads (id, title, course, author, author_role, views, tags, solved, last_activity, content, created_at) VALUES ('ft1', 'How does AVL tree rotation work in practice?', 'CS301', 'Alex Johnson', 'student', 42, CAST('["trees","avl","rotation"]' AS jsonb), TRUE, '2 hours ago', 'I''m struggling to understand when and how AVL tree rotations are triggered.', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.forum_threads (id, title, course, author, author_role, views, tags, solved, last_activity, content, created_at) VALUES ('ft2', 'Difference between 2NF and 3NF?', 'CS302', 'Maria Garcia', 'student', 28, CAST('["normalization","2nf","3nf"]' AS jsonb), FALSE, '5 hours ago', 'Can someone explain the practical difference between 2NF and 3NF with an example?', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.forum_threads (id, title, course, author, author_role, views, tags, solved, last_activity, content, created_at) VALUES ('ft3', 'Why does Round Robin cause more context switches?', 'CS303', 'Alex Johnson', 'student', 19, CAST('["scheduling","round-robin"]' AS jsonb), FALSE, '1 day ago', 'I understand Round Robin is fair, but why does it cause more context switches than FCFS?', '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.forum_replies (id, thread_id, author, author_role, content, timestamp) VALUES ('r1', 'ft1', 'Dr. Sarah Mitchell', 'lecturer', 'AVL rotations are triggered when the balance factor becomes +2 or -2.', '1 hour ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.forum_replies (id, thread_id, author, author_role, content, timestamp) VALUES ('r2', 'ft1', 'Maria Garcia', 'student', 'Great explanation! So a single rotation handles LL and RR cases?', '30 min ago') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.forum_replies (id, thread_id, author, author_role, content, timestamp) VALUES ('r3', 'ft2', 'Prof. James Carter', 'lecturer', '2NF removes partial dependencies; 3NF additionally removes transitive dependencies.', '4 hours ago') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.analytics_snapshots (id, user_id, overall_grade, quiz_average, study_hours, assignments_done, assignments_total, day_streak, courses_active, weekly_progress, recent_quiz_scores, subject_strengths, radar_data, updated_at) VALUES ('an1', 'u1', 78.4, 75.3, 42, 3, 7, 7, 4, CAST('[{"day":"Mon","hours":2.5,"score":72},{"day":"Tue","hours":3,"score":78},{"day":"Wed","hours":1.5,"score":65},{"day":"Thu","hours":4,"score":85},{"day":"Fri","hours":2,"score":74},{"day":"Sat","hours":3.5,"score":80},{"day":"Sun","hours":1,"score":70}]' AS jsonb), CAST('[{"quiz":"BST Quiz","score":67,"course":"CS301"},{"quiz":"SQL Basics","score":82,"course":"CS302"},{"quiz":"Process Scheduling","score":71,"course":"CS303"},{"quiz":"Network Protocols","score":88,"course":"CS304"}]' AS jsonb), CAST('[{"subject":"CS301 - DSA","score":72,"status":"good"},{"subject":"CS302 - DBMS","score":85,"status":"excellent"},{"subject":"CS303 - OS","score":61,"status":"needs-work"},{"subject":"CS304 - Networks","score":78,"status":"good"}]' AS jsonb), CAST('[{"subject":"DSA","score":72},{"subject":"DBMS","score":85},{"subject":"OS","score":61},{"subject":"Networks","score":78},{"subject":"Quizzes","score":75},{"subject":"Assignments","score":80}]' AS jsonb), '2026-09-13 17:10:49') ON CONFLICT (id) DO NOTHING;
